### ISSUE TITLE
version v0.6.1-RC1启动时指定了错误的参数会报错

### ISSUE THREAD

**Issue by zixijian** [mudclient/go-mud#24]
误用参数-h报错信息

```
[~]$ ./go-mud -h 123.57.24.152
GoMud(version v0.6.1-RC1)

Usage:
  ./go-mud [flags]

Flags:
  -c, --config FILENAME            config FILENAME, default to `config.yaml` or `config.json`
      --version                    just print version number only
      --help                       show this message
      --gen-yaml                   generate config.yaml
      --gen-json                   generate config.json
      --ui.ambiguouswidth string   二义性字符宽度，可选值: auto/single/double/space (default "auto")
      --ui.historylines int        历史记录保留行数 (default 100000)
      --ui.rttvheight int          历史查看模式下实时文本区域高度 (default 10)
  -H, --mud.host IP/Domain         服务器 IP/Domain (default "mud.pkuxkx.net")
  -P, --mud.port Port              服务器 Port (default 8080)
      --lua.enable                 是否加载 Lua 机器人 (default true)
  -p, --lua.path path              Lua 插件路径 path (default "lua")
panic: runtime error: index out of range [-1]

goroutine 22 [running]:
github.com/dzpao/go-mud/ui.(*UI).Print(0x4000190580, 0x4000093e18, 0x1, 0x1, 0x0, 0x0, 0x0)
        github.com/dzpao/go-mud@/ui/ui.go:342 +0x46c
github.com/dzpao/go-mud/ui.(*UI).Println(0x4000190580, 0x400021da60, 0x1, 0x1, 0xee6b2800, 0x0, 0x0)
        github.com/dzpao/go-mud@/ui/ui.go:364 +0x84
github.com/dzpao/go-mud/mud.(*MudServer).Run(0x40001f8480)
        github.com/dzpao/go-mud@/mud/mud.go:67 +0x95c
created by main.(*Client).Run
        github.com/dzpao/go-mud@/main.go:67 +0x238
```

**Comment by dzpao** [comment]
了解了。我会尽快解决。

BTW：发文时可以用 markdown 语法。这样排版好看一点。
