### ISSUE TITLE
当使用 Ctrl+C 结束回滚分屏时，优先调用了终端的 Ctrl+C 效果，直接退出 gomud

### ISSUE THREAD

**Issue by zhenhua-feng** [mudclient/go-mud#38]
重现方法：
启动go-mud连接服务器，exit退回终端，重复多次后在游戏界面输入 Ctrl+C

$ ~/go-mud/go-mud --mud.encoding GBK -c ~/go-mud/profile/JHL/config.json
$ ~/go-mud/go-mud --mud.encoding GBK -c ~/go-mud/profile/JHL/config.json
$ ~/go-mud/go-mud --mud.encoding GBK -c ~/go-mud/profile/JHL/config.json
panic: runtime error: slice bounds out of range [-3:] [recovered]
	panic: runtime error: slice bounds out of range [-3:]

goroutine 10 [running]:
github.com/rivo/tview.(*Application).Run.func1(0xc000106580)
	github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/application.go:149 +0x82
panic(0x162c400, 0xc000528000)
	runtime/panic.go:679 +0x1b2
github.com/mudclient/go-mud/ui.(*UI).stopScrolling(0xc0000b6580)
	github.com/mudclient/go-mud@/ui/ui.go:239 +0x235
github.com/mudclient/go-mud/ui.(*UI).InputCapture(0xc0000b6580, 0xc0002a6000, 0xc000106580)
	github.com/mudclient/go-mud@/ui/ui.go:118 +0x5d
github.com/rivo/tview.(*Application).Run(0xc000106580, 0x0, 0x0)
	github.com/rivo/tview@v0.0.0-20190829161255-f8bc69b90341/application.go:219 +0x486
github.com/mudclient/go-mud/ui.(*UI).Run(0xc0000b6580)
	github.com/mudclient/go-mud@/ui/ui.go:197 +0x67
created by main.(*Client).Run
	github.com/mudclient/go-mud@/main.go:66 +0x202

**Comment by dzpao** [comment]
确认存在此 BUG
