### ISSUE TITLE
0.51 arm64版本运行异常

### ISSUE THREAD

**Issue by zixijian** [mudclient/go-mud#9]
异常后shell错位，无法键入命令
```
命令: panic: runtime error: invalid memory address or nil pointer dereference                                                                                   [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x166870]

                                                                 goroutine 24 [running]:
     github.com/yuin/gopher-lua.(*LState).metatable(0x400009e820, 0x0, 0x0, 0x1b201, 0x4000056d01, 0x0)
                        /Users/flw/.go/src/github.com/yuin/gopher-lua/state.go:630 +0x250
      github.com/yuin/gopher-lua.(*LState).metaOp1(0x400009e820, 0x0, 0x0, 0x29dc6a, 0x6, 0x0, 0x2)
                        /Users/flw/.go/src/github.com/yuin/gopher-lua/state.go:649 +0x40
     github.com/yuin/gopher-lua.(*LState).metaCall(0x400009e820, 0x0, 0x0, 0x40002ec1e0, 0x4a)
                /Users/flw/.go/src/github.com/yuin/gopher-lua/state.go:677 +0x64
                                                                                github.com/yuin/gopher-lua.(*LState).callR(0x400009e820, 0x2, 0x0, 0x0)
                                                                        /Users/flw/.go/src/github.com/yuin/gopher-lua/state.go:859 +0x8c
                                                     github.com/yuin/gopher-lua.(*LState).Call(...)
                        /Users/flw/.go/src/github.com/yuin/gopher-lua/state.go:1613                                                                                  github.com/yuin/gopher-lua.(*LState).CallByParam(0x400009e820, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4000056ed0, 0x2, 0x2, 0x50, ...)
                                        /Users/flw/.go/src/github.com/yuin/gopher-lua/state.go:1696 +0x154
                       main.(*LuaRobot).OnReceive(0x4000114630, 0x40000aa2d0, 0x4a, 0x40002ec230, 0x4a)
                        /Users/flw/code/git/github/go-mud/main.go:120 +0xec
                                                                           main.main.func2(0x4000095260)
                        /Users/flw/code/git/github/go-mud/main.go:335 +0x198
                                                                            created by main.main
                /Users/flw/code/git/github/go-mud/main.go:330 +0x288
   ```

**Comment by dzpao** [comment]
OK，我已知悉。看起来这块的容错处理有问题，应当有一个更为友好的错误提示方便定位才好。

**Comment by dzpao** [comment]
应当是有一行代码写错了位置。
你现在再测试一下。

**Comment by dzpao** [comment]
经过验证，已经解决。
错误信息也在 ca7b1ca9 中进行了妥善处理。
